[package]
name = "ceres"
version = "0.0.1"
authors = ["Lukas Pustina <lukas@pustina.net>"]

[badges]
travis-ci = { repository = "lukaspustina/ceres", branch = "master" }
codecov = { repository = "lukaspustina/ceres", branch = "master", service = "github" }

[dependencies]
clap = "^2.30"
error-chain = "^0.11"
log = "0.4"
loggerv = "0.7"
prettytable-rs = "^0.6"
regex = "0.2"
rusoto_core = "0.31.0"
rusoto_credential = "0.10.0"
rusoto_ec2 = "0.31.0"
rusoto_sts = "0.31.0"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
toml = "^0.4"

[dev-dependencies]
spectral = "^0.6"
quickcheck = "^0.6"
