[package]
name = "ceres"
version = "0.0.1"
authors = ["Lukas Pustina <lukas@pustina.net>"]

[dependencies]
clap = "^2.30"
env_logger = "0.5"
error-chain = "^0.11"
log = "0.4"
regex = "0.2"
rusoto_core = "0.31.0"
rusoto_ec2 = "0.31.0"
rusoto_sts = "0.31.0"
tabwriter = "^1.0"
