[package]
name = "ceres"
version = "0.0.1"
authors = ["Lukas Pustina <lukas@pustina.net>"]

[dependencies]
env_logger = "0.5"
log = "0.4"
rusoto_core = "0.31.0"
rusoto_ec2 = "0.31.0"
rusoto_sts = "0.31.0"

