= CEnteRdEvice Sre (ceres)
:toc: macro
Ceres the goddess of agriculture, grain crops, fertility and motherly relationships.

image:https://dev.azure.com/centerdevice/ceres/_apis/build/status/CenterDevice.ceres?branchName=master[link="https://dev.azure.com/centerdevice/ceres/_build/latest?definitionId=11&branchName=master"] image:https://img.shields.io/github/release/centerdevice/ceres.svg[link="https://github.com/centerdevice/ceres/releases"] image:https://img.shields.io/crates/v/ceres.svg[link="https://crates.io/crates/ceres"] image:https://img.shields.io/badge/license-MIT-blue.svg?label=License[link="./LICENSE]

toc::[]

== Installation

=== Ubuntu [x86_64]

Please add my PackageCloud open source repository and install `ceres` via apt.

[source,bash]
----
curl -s https://packagecloud.io/install/repositories/centerdevice/opensource/script.deb.sh | sudo bash
sudo apt-get install ceres
----

=== Linux Binaries [x86_64]

There are binaries available at the https://github.com/centerdevice/ceres/releases[GitHub release] page. The binaries are compiled on Ubuntu.

=== macOS Binaries [x86_64]

There are binaries available at the https://github.com/centerdevice/ceres/releases[GitHub release] page.

=== Brew

First, install https://www.rustup.rs[Rustup] to install a Rust compiler.

==== Latest Release

`brew install centerdevice/os/ceres`

==== HEAD

`brew install centerdevice/os/ceres --HEAD`

=== Cargo

First, install https://www.rustup.rs[Rustup] to install a Rust compiler.

`cargo install ceres --git https://github.com/centerdevice/ceres`

=== From Source

First, install https://www.rustup.rs[Rustup] to install a Rust compiler.

[source,bash]
----
git clone https://github.com/centerdevice/ceres
cd ceres
make install
----


== Configuration

`ceres` requires a configuration file in order to load profiles. By default, `ceres` tries to read `~/.ceres.conf`. See this link:examples/ceres.conf[example] for an example configuration and the corresponding configuration link:docs/ceres.conf.5.md[description].


== Use Cases

Ceres currently supports the following modules:

* `centerdevice` Access CenterDevice from the CLI
* `completions` Generate shell completion scripts
* `consul` Do stuff of consul
* `health` CenterDevice Health Status
* `infrastructure` Do stuff with infrastructure repos
* `instances` Do stuff with instances
* `ops` Do ops stuff
* `statuspages` Status information from statuspage.io
* `stories` Manage stories

See the link:docs/ceres.1.md[man page] for details.

